language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -extension RANDR &> /dev/null &
    - wget -c http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar -O selenium.jar
    - java -jar selenium.jar > /dev/null &

    - php -S localhost:8080 -t fixtures/www 2> /dev/null &
    - composer install

script: ./bin/behat -fprogress
